### ISSUE TITLE
Manually trigger update() from controller

### ISSUE THREAD

**Issue by kenny1har** [yads/ngTinyScrollbar#14]
After updating DOM elements, how do I manually trigger update() from the controller ?

thanks.

**Comment by yads** [comment]
In your directive, you can require `scrollbar`, then use it in your link method for example:

```
angular.module('myDirectives', [])
    .directive('myDirective', function() {
         return {
              require: 'scrollbar',
              link: function(scope, element, attrs, scrollbar) {
                  scrollbar.update();
              }
         };
     });
```

**Comment by yads** [comment]
Closing due to lack of updates.

**Comment by anuja-joshi** [comment]
@yads  this directive throws an error ``` angular.js:13550 Error: [$compile:ctreq] Controller 'scrollbar', required by directive 'myDirectives', can't be found! ``` 
angular version:  1.5.5
ngTinyScrollbar version:  0.9.1

**Comment by lashisu** [comment]
Any Update in this?

**Comment by yads** [comment]
I've updated the example, all it needed was to add the ngTinyScrollbar as a dependency module.
