### ISSUE TITLE
How can I add ngTinyScrollbar 

### ISSUE THREAD

**Issue by Alandrius** [yads/ngTinyScrollbar#24]
Please assist how can I add tinyScrollbar to https://github.com/ghiden/angucomplete-alt dropdown list?

**Comment by yads** [comment]
I don't think that it would be possible to do this given the way both modules are set up.

**Comment by Alandrius** [comment]
Can I add scrollbar attribute to some element dynamically on window.onload event and then apply TinyScrollbar functionality to the element in some way?
