### ISSUE TITLE
Slow in Linux

### ISSUE THREAD

**Issue by brunowego** [yads/ngTinyScrollbar#30]
I get different experience in windows and linux. In linux is very slow when scroll down the page. Try test with Ubuntu LTS. Thanks!

**Comment by yads** [comment]
Which browser?

**Comment by brunowego** [comment]
FF 31.6 :+1:

**Comment by yads** [comment]
What is the setup that's giving you issues, ie the markup/options etc.

**Comment by brunowego** [comment]
The own demo @yads.

**Comment by yads** [comment]
Ah it looks like the demo must be out of date, it works fine locally. I'll look at migrating to githubpages. Thanks for bringing this to my attention.

**Comment by yads** [comment]
@brunowego Demo updated, let me know if it's still an issue for you.

**Comment by brunowego** [comment]
Works, thanks @yads :+1:
